package com.qrware.repository.qr;

import com.qrware.domain.qr.QRCodeData;
import com.qrware.domain.qr.QRCodeType;
import com.qrware.repository.BaseRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Repository interface for QRCodeData entity operations
 */
@Repository
public interface QRCodeDataRepository extends BaseRepository<QRCodeData> {

    /**
     * Find QR code by code
     */
    Optional<QRCodeData> findByCode(String code);

    /**
     * Check if QR code exists
     */
    boolean existsByCode(String code);

    /**
     * Check if QR code exists excluding current QR code
     */
    @Query("SELECT CASE WHEN COUNT(q) > 0 THEN true ELSE false END FROM QRCodeData q WHERE q.code = :code AND q.id != :qrCodeId")
    boolean existsByCodeAndIdNot(@Param("code") String code, @Param("qrCodeId") Long qrCodeId);

    /**
     * Find QR codes by type
     */
    List<QRCodeData> findByType(QRCodeType type);

    /**
     * Find QR codes by type and active status
     */
    List<QRCodeData> findByTypeAndActive(QRCodeType type, Boolean active);

    /**
     * Find QR codes by entity type and entity ID
     */
    Optional<QRCodeData> findByEntityTypeAndEntityId(String entityType, Long entityId);

    /**
     * Find QR codes by entity type
     */
    List<QRCodeData> findByEntityType(String entityType);

    /**
     * Find QR codes by entity ID
     */
    List<QRCodeData> findByEntityId(Long entityId);

    /**
     * Find all active QR codes
     */
    List<QRCodeData> findByActiveTrue();

    /**
     * Find all inactive QR codes
     */
    List<QRCodeData> findByActiveFalse();

    /**
     * Find expired QR codes
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.expiresAt IS NOT NULL AND q.expiresAt < CURRENT_TIMESTAMP")
    List<QRCodeData> findExpiredQRCodes();

    /**
     * Find QR codes expiring soon
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.expiresAt IS NOT NULL AND q.expiresAt BETWEEN CURRENT_TIMESTAMP AND :expiryDate")
    List<QRCodeData> findQRCodesExpiringSoon(@Param("expiryDate") LocalDateTime expiryDate);

    /**
     * Find QR codes expiring within hours
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.expiresAt IS NOT NULL AND q.expiresAt BETWEEN CURRENT_TIMESTAMP AND :endDate")
    List<QRCodeData> findQRCodesExpiringWithinHours(@Param("endDate") LocalDateTime endDate);

    /**
     * Find valid QR codes (active and not expired)
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.active = true AND (q.expiresAt IS NULL OR q.expiresAt > CURRENT_TIMESTAMP)")
    List<QRCodeData> findValidQRCodes();

    /**
     * Find QR codes never scanned
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.lastScanned IS NULL")
    List<QRCodeData> findNeverScannedQRCodes();

    /**
     * Find QR codes not scanned recently
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.lastScanned IS NULL OR q.lastScanned < :date")
    List<QRCodeData> findQRCodesNotScannedSince(@Param("date") LocalDateTime date);

    /**
     * Find QR codes scanned recently
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.lastScanned >= :date")
    List<QRCodeData> findQRCodesScannedSince(@Param("date") LocalDateTime date);

    /**
     * Find frequently scanned QR codes
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.scanCount >= :threshold ORDER BY q.scanCount DESC")
    List<QRCodeData> findFrequentlyScannedQRCodes(@Param("threshold") Long threshold);

    /**
     * Find QR codes by scan count range
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.scanCount BETWEEN :minCount AND :maxCount ORDER BY q.scanCount DESC")
    List<QRCodeData> findByScanCountBetween(@Param("minCount") Long minCount, @Param("maxCount") Long maxCount);

    /**
     * Find QR codes by format
     */
    List<QRCodeData> findByFormat(String format);

    /**
     * Find QR codes by size
     */
    List<QRCodeData> findBySize(Integer size);

    /**
     * Find QR codes by generated by user
     */
    List<QRCodeData> findByGeneratedBy(String generatedBy);

    /**
     * Find QR codes by generation reason
     */
    @Query("SELECT q FROM QRCodeData q WHERE LOWER(q.generationReason) LIKE LOWER(CONCAT('%', :reason, '%'))")
    List<QRCodeData> findByGenerationReasonContaining(@Param("reason") String reason);

    /**
     * Find QR codes by description containing keyword
     */
    @Query("SELECT q FROM QRCodeData q WHERE LOWER(q.description) LIKE LOWER(CONCAT('%', :keyword, '%'))")
    List<QRCodeData> findByDescriptionContaining(@Param("keyword") String keyword);

    /**
     * Search QR codes by code, description, or entity type
     */
    @Query("SELECT q FROM QRCodeData q WHERE " +
           "LOWER(q.code) LIKE LOWER(CONCAT('%', :searchTerm, '%')) OR " +
           "LOWER(q.description) LIKE LOWER(CONCAT('%', :searchTerm, '%')) OR " +
           "LOWER(q.entityType) LIKE LOWER(CONCAT('%', :searchTerm, '%'))")
    List<QRCodeData> searchQRCodes(@Param("searchTerm") String searchTerm);

    /**
     * Find QR codes with custom data
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.customData IS NOT NULL AND q.customData != ''")
    List<QRCodeData> findQRCodesWithCustomData();

    /**
     * Find QR codes with metadata
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.metadata IS NOT NULL AND q.metadata != ''")
    List<QRCodeData> findQRCodesWithMetadata();

    /**
     * Find QR codes with image path
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.imagePath IS NOT NULL AND q.imagePath != ''")
    List<QRCodeData> findQRCodesWithImagePath();

    /**
     * Find QR codes without image path
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.imagePath IS NULL OR q.imagePath = ''")
    List<QRCodeData> findQRCodesWithoutImagePath();

    /**
     * Find QR codes by creation date range
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.createdAt BETWEEN :startDate AND :endDate ORDER BY q.createdAt DESC")
    List<QRCodeData> findByCreationDateBetween(@Param("startDate") LocalDateTime startDate, @Param("endDate") LocalDateTime endDate);

    /**
     * Find QR codes created after date
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.createdAt >= :date ORDER BY q.createdAt DESC")
    List<QRCodeData> findCreatedAfter(@Param("date") LocalDateTime date);

    /**
     * Count QR codes by type
     */
    long countByType(QRCodeType type);

    /**
     * Count active QR codes
     */
    long countByActiveTrue();

    /**
     * Count inactive QR codes
     */
    long countByActiveFalse();

    /**
     * Count expired QR codes
     */
    @Query("SELECT COUNT(q) FROM QRCodeData q WHERE q.expiresAt IS NOT NULL AND q.expiresAt < CURRENT_TIMESTAMP")
    long countExpiredQRCodes();

    /**
     * Count QR codes expiring soon
     */
    @Query("SELECT COUNT(q) FROM QRCodeData q WHERE q.expiresAt IS NOT NULL AND q.expiresAt BETWEEN CURRENT_TIMESTAMP AND :expiryDate")
    long countQRCodesExpiringSoon(@Param("expiryDate") LocalDateTime expiryDate);

    /**
     * Count valid QR codes
     */
    @Query("SELECT COUNT(q) FROM QRCodeData q WHERE q.active = true AND (q.expiresAt IS NULL OR q.expiresAt > CURRENT_TIMESTAMP)")
    long countValidQRCodes();

    /**
     * Count never scanned QR codes
     */
    @Query("SELECT COUNT(q) FROM QRCodeData q WHERE q.lastScanned IS NULL")
    long countNeverScannedQRCodes();

    /**
     * Count QR codes by entity type
     */
    long countByEntityType(String entityType);

    /**
     * Get total scan count
     */
    @Query("SELECT SUM(q.scanCount) FROM QRCodeData q")
    Long getTotalScanCount();

    /**
     * Get QR code statistics
     */
    @Query("SELECT " +
           "COUNT(q) as totalQRCodes, " +
           "SUM(CASE WHEN q.active = true THEN 1 ELSE 0 END) as activeQRCodes, " +
           "SUM(CASE WHEN q.expiresAt IS NOT NULL AND q.expiresAt < CURRENT_TIMESTAMP THEN 1 ELSE 0 END) as expiredQRCodes, " +
           "SUM(CASE WHEN q.lastScanned IS NULL THEN 1 ELSE 0 END) as neverScannedQRCodes, " +
           "SUM(q.scanCount) as totalScans, " +
           "COUNT(DISTINCT q.entityType) as uniqueEntityTypes " +
           "FROM QRCodeData q")
    Object[] getQRCodeStatistics();

    /**
     * Get QR code statistics by type
     */
    @Query("SELECT q.type, COUNT(q), " +
           "SUM(CASE WHEN q.active = true THEN 1 ELSE 0 END) as activeCount, " +
           "SUM(q.scanCount) as totalScans, " +
           "AVG(q.scanCount) as avgScans " +
           "FROM QRCodeData q GROUP BY q.type ORDER BY q.type")
    List<Object[]> getQRCodeStatsByType();

    /**
     * Get QR code statistics by entity type
     */
    @Query("SELECT q.entityType, COUNT(q), " +
           "SUM(CASE WHEN q.active = true THEN 1 ELSE 0 END) as activeCount, " +
           "SUM(q.scanCount) as totalScans, " +
           "AVG(q.scanCount) as avgScans " +
           "FROM QRCodeData q GROUP BY q.entityType ORDER BY q.entityType")
    List<Object[]> getQRCodeStatsByEntityType();

    /**
     * Get QR code usage statistics by date
     */
    @Query("SELECT DATE(q.lastScanned), COUNT(q) " +
           "FROM QRCodeData q " +
           "WHERE q.lastScanned BETWEEN :startDate AND :endDate " +
           "GROUP BY DATE(q.lastScanned) ORDER BY DATE(q.lastScanned)")
    List<Object[]> getQRCodeUsageByDate(@Param("startDate") LocalDateTime startDate, @Param("endDate") LocalDateTime endDate);

    /**
     * Get most scanned QR codes
     */
    @Query("SELECT q FROM QRCodeData q ORDER BY q.scanCount DESC")
    List<QRCodeData> getMostScannedQRCodes();

    /**
     * Get recently scanned QR codes
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.lastScanned IS NOT NULL ORDER BY q.lastScanned DESC")
    List<QRCodeData> getRecentlyScannedQRCodes();

    /**
     * Find QR codes created by user
     */
    @Query("SELECT q FROM QRCodeData q WHERE q.createdBy = :username")
    List<QRCodeData> findCreatedBy(@Param("username") String username);

    /**
     * Find most recently created QR codes
     */
    @Query("SELECT q FROM QRCodeData q ORDER BY q.createdAt DESC")
    List<QRCodeData> findMostRecentlyCreated();

    /**
     * Find QR codes that can be cleaned up (inactive and old)
     */
    @Query("SELECT q FROM QRCodeData q WHERE " +
           "q.active = false AND " +
           "q.createdAt < :cutoffDate AND " +
           "(q.lastScanned IS NULL OR q.lastScanned < :cutoffDate)")
    List<QRCodeData> findQRCodesForCleanup(@Param("cutoffDate") LocalDateTime cutoffDate);

    /**
     * Find duplicate QR codes by entity
     */
    @Query("SELECT q FROM QRCodeData q WHERE EXISTS " +
           "(SELECT q2 FROM QRCodeData q2 WHERE q2.id != q.id AND q2.entityType = q.entityType AND q2.entityId = q.entityId)")
    List<QRCodeData> findDuplicateQRCodes();

    /**
     * Find orphaned QR codes (no corresponding entity)
     */
    @Query("SELECT q FROM QRCodeData q WHERE " +
           "(q.entityType = 'PRODUCT' AND NOT EXISTS (SELECT p FROM Product p WHERE p.id = q.entityId)) OR " +
           "(q.entityType = 'LOCATION' AND NOT EXISTS (SELECT l FROM Location l WHERE l.id = q.entityId)) OR " +
           "(q.entityType = 'INVENTORY_ITEM' AND NOT EXISTS (SELECT i FROM InventoryItem i WHERE i.id = q.entityId))")
    List<QRCodeData> findOrphanedQRCodes();

    /**
     * Find all unique entity types
     */
    @Query("SELECT DISTINCT q.entityType FROM QRCodeData q ORDER BY q.entityType")
    List<String> findAllEntityTypes();

    /**
     * Find all unique formats
     */
    @Query("SELECT DISTINCT q.format FROM QRCodeData q WHERE q.format IS NOT NULL ORDER BY q.format")
    List<String> findAllFormats();

    /**
     * Find all unique sizes
     */
    @Query("SELECT DISTINCT q.size FROM QRCodeData q WHERE q.size IS NOT NULL ORDER BY q.size")
    List<Integer> findAllSizes();

    /**
     * Update scan statistics
     */
    @Query("UPDATE QRCodeData q SET q.scanCount = q.scanCount + 1, q.lastScanned = CURRENT_TIMESTAMP WHERE q.id = :qrCodeId")
    void updateScanStatistics(@Param("qrCodeId") Long qrCodeId);

    /**
     * Deactivate expired QR codes
     */
    @Query("UPDATE QRCodeData q SET q.active = false WHERE q.expiresAt IS NOT NULL AND q.expiresAt < CURRENT_TIMESTAMP")
    int deactivateExpiredQRCodes();

    /**
     * Reset scan count for QR code
     */
    @Query("UPDATE QRCodeData q SET q.scanCount = 0, q.lastScanned = NULL WHERE q.id = :qrCodeId")
    void resetScanCount(@Param("qrCodeId") Long qrCodeId);

    /**
     * Find QR codes by entity reference
     */
    @Query("SELECT q FROM QRCodeData q WHERE CONCAT(q.entityType, ':', q.entityId) = :entityReference")
    List<QRCodeData> findByEntityReference(@Param("entityReference") String entityReference);

    /**
     * Get scan velocity (scans per hour) for QR code
     */
    @Query("SELECT q.scanCount * 1.0 / (EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - q.createdAt)) / 3600) " +
           "FROM QRCodeData q WHERE q.id = :qrCodeId AND q.createdAt IS NOT NULL")
    Double getScanVelocity(@Param("qrCodeId") Long qrCodeId);
}