CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(500),
    parent_id BIGINT,
    active BOOLEAN NOT NULL,
    sort_order INT,
    icon VARCHAR(50),
    color VARCHAR(7),
    requires_special_handling BOOLEAN NOT NULL,
    storage_temperature_min INT,
    storage_temperature_max INT,
    storage_humidity_min INT,
    storage_humidity_max INT,
    FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE INDEX idx_category_name ON categories(name);
CREATE INDEX idx_category_code ON categories(code);
CREATE INDEX idx_category_parent ON categories(parent_id);
CREATE INDEX idx_category_active ON categories(active);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    sku VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    barcode VARCHAR(50),
    category_id BIGINT NOT NULL,
    price DECIMAL(10, 2),
    cost DECIMAL(10, 2),
    weight DECIMAL(8, 3),
    dimensions_length DECIMAL(8, 2),
    dimensions_width DECIMAL(8, 2),
    dimensions_height DECIMAL(8, 2),
    unit_of_measure VARCHAR(20) NOT NULL,
    minimum_stock INT NOT NULL,
    maximum_stock INT,
    reorder_point INT,
    active BOOLEAN NOT NULL,
    perishable BOOLEAN NOT NULL,
    hazardous BOOLEAN NOT NULL,
    fragile BOOLEAN NOT NULL,
    manufacturer VARCHAR(100),
    supplier VARCHAR(100),
    storage_conditions VARCHAR(500),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE INDEX idx_product_sku ON products(sku);
CREATE INDEX idx_product_barcode ON products(barcode);
CREATE INDEX idx_product_name ON products(name);
CREATE INDEX idx_product_category ON products(category_id);
CREATE INDEX idx_product_active ON products(active);

CREATE TABLE zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(500),
    type VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL,
    temperature_controlled BOOLEAN NOT NULL,
    temperature_min INT,
    temperature_max INT,
    humidity_controlled BOOLEAN NOT NULL,
    humidity_min INT,
    humidity_max INT,
    security_level INT NOT NULL,
    hazardous_materials BOOLEAN NOT NULL,
    fragile_items BOOLEAN NOT NULL,
    picking_priority INT,
    manager VARCHAR(100),
    contact_info VARCHAR(200),
    color VARCHAR(7)
);

CREATE INDEX idx_zone_name ON zones(name);
CREATE INDEX idx_zone_code ON zones(code);
CREATE INDEX idx_zone_type ON zones(type);
CREATE INDEX idx_zone_active ON zones(active);

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    zone_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    aisle VARCHAR(10),
    rack VARCHAR(10),
    shelf VARCHAR(10),
    bin VARCHAR(10),
    capacity_volume DECIMAL(10, 3),
    capacity_weight DECIMAL(10, 3),
    capacity_items INT,
    temperature_controlled BOOLEAN NOT NULL,
    temperature_min INT,
    temperature_max INT,
    humidity_controlled BOOLEAN NOT NULL,
    humidity_min INT,
    humidity_max INT,
    hazardous_materials BOOLEAN NOT NULL,
    fragile_items BOOLEAN NOT NULL,
    security_level INT NOT NULL,
    active BOOLEAN NOT NULL,
    pickable BOOLEAN NOT NULL,
    receivable BOOLEAN NOT NULL,
    qr_code VARCHAR(100) UNIQUE,
    barcode VARCHAR(50),
    x_coordinate DECIMAL(10, 2),
    y_coordinate DECIMAL(10, 2),
    z_coordinate DECIMAL(10, 2),
    FOREIGN KEY (zone_id) REFERENCES zones(id)
);

CREATE INDEX idx_location_code ON locations(code);
CREATE INDEX idx_location_zone ON locations(zone_id);
CREATE INDEX idx_location_type ON locations(type);
CREATE INDEX idx_location_active ON locations(active);
CREATE INDEX idx_location_coordinates ON locations(aisle, rack, shelf, bin);

CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    product_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    reserved_quantity INT NOT NULL,
    available_quantity INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    qr_code VARCHAR(100) NOT NULL UNIQUE,
    lot_number VARCHAR(50),
    batch_number VARCHAR(50),
    serial_number VARCHAR(50),
    received_date DATE NOT NULL,
    expiry_date DATE,
    manufacture_date DATE,
    last_counted_date TIMESTAMP,
    last_moved_date TIMESTAMP,
    unit_cost DECIMAL(10, 2),
    total_cost DECIMAL(12, 2),
    supplier_reference VARCHAR(100),
    purchase_order_number VARCHAR(50),
    notes TEXT,
    temperature INT,
    humidity INT,
    condition_rating INT,
    quarantine BOOLEAN NOT NULL,
    quarantine_reason VARCHAR(500),
    hold BOOLEAN NOT NULL,
    hold_reason VARCHAR(500),
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (location_id) REFERENCES locations(id)
);

CREATE INDEX idx_inventory_product ON inventory_items(product_id);
CREATE INDEX idx_inventory_location ON inventory_items(location_id);
CREATE INDEX idx_inventory_status ON inventory_items(status);
CREATE INDEX idx_inventory_qr_code ON inventory_items(qr_code);
CREATE INDEX idx_inventory_lot_number ON inventory_items(lot_number);
CREATE INDEX idx_inventory_expiry_date ON inventory_items(expiry_date);

CREATE TABLE movement_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    inventory_item_id BIGINT NOT NULL,
    movement_type VARCHAR(20) NOT NULL,
    movement_date TIMESTAMP NOT NULL,
    quantity_before INT,
    quantity_after INT,
    quantity_changed INT NOT NULL,
    from_location_id BIGINT,
    to_location_id BIGINT,
    status_before VARCHAR(20),
    status_after VARCHAR(20),
    unit_cost DECIMAL(10, 2),
    total_cost DECIMAL(12, 2),
    reference_number VARCHAR(50),
    reference_type VARCHAR(20),
    reason VARCHAR(500),
    notes TEXT,
    user_id VARCHAR(50),
    user_name VARCHAR(100),
    approved BOOLEAN NOT NULL,
    approved_by VARCHAR(50),
    approved_date TIMESTAMP,
    batch_id VARCHAR(50),
    system_generated BOOLEAN NOT NULL,
    temperature INT,
    humidity INT,
    weight DECIMAL(10, 3),
    volume DECIMAL(10, 3),
    FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id),
    FOREIGN KEY (from_location_id) REFERENCES locations(id),
    FOREIGN KEY (to_location_id) REFERENCES locations(id)
);

CREATE INDEX idx_movement_inventory_item ON movement_history(inventory_item_id);
CREATE INDEX idx_movement_type ON movement_history(movement_type);
CREATE INDEX idx_movement_date ON movement_history(movement_date);
CREATE INDEX idx_movement_from_location ON movement_history(from_location_id);
CREATE INDEX idx_movement_to_location ON movement_history(to_location_id);
CREATE INDEX idx_movement_reference ON movement_history(reference_number);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    active BOOLEAN NOT NULL,
    email_verified BOOLEAN NOT NULL,
    last_login TIMESTAMP,
    failed_login_attempts INT,
    locked_until TIMESTAMP
);

CREATE INDEX idx_user_username ON users(username);
CREATE INDEX idx_user_email ON users(email);
CREATE INDEX idx_user_active ON users(active);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    active BOOLEAN NOT NULL
);

CREATE INDEX idx_role_name ON roles(name);

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    resource VARCHAR(50) NOT NULL,
    action VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE INDEX idx_permission_name ON permissions(name);
CREATE INDEX idx_permission_resource ON permissions(resource);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(id),
    FOREIGN KEY (permission_id) REFERENCES permissions(id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    priority VARCHAR(10) NOT NULL,
    description VARCHAR(500),
    creator_id BIGINT NOT NULL,
    assigned_to BIGINT,
    source_location_id BIGINT,
    destination_location_id BIGINT,
    expected_date TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    cancellation_reason VARCHAR(1000),
    total_items INT,
    completed_items INT,
    estimated_value DECIMAL(15, 2),
    notes VARCHAR(1000),
    external_reference VARCHAR(200),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (assigned_to) REFERENCES users(id),
    FOREIGN KEY (source_location_id) REFERENCES locations(id),
    FOREIGN KEY (destination_location_id) REFERENCES locations(id)
);

CREATE INDEX idx_order_number ON orders(order_number);
CREATE INDEX idx_order_status ON orders(status);
CREATE INDEX idx_order_type ON orders(type);
CREATE INDEX idx_order_creator ON orders(creator_id);
CREATE INDEX idx_order_assigned_to ON orders(assigned_to);
CREATE INDEX idx_order_expected_date ON orders(expected_date);
CREATE INDEX idx_order_priority ON orders(priority);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    order_id BIGINT NOT NULL,
    line_number INT NOT NULL,
    product_id BIGINT NOT NULL,
    inventory_item_id BIGINT,
    source_location_id BIGINT,
    destination_location_id BIGINT,
    requested_quantity INT NOT NULL,
    completed_quantity INT NOT NULL,
    unit_price DECIMAL(15, 4),
    status VARCHAR(20) NOT NULL,
    notes VARCHAR(500),
    batch_number VARCHAR(200),
    serial_number VARCHAR(200),
    expiry_date TIMESTAMP,
    picked_at TIMESTAMP,
    completed_at TIMESTAMP,
    completion_notes VARCHAR(500),
    qr_code_data VARCHAR(200) UNIQUE,
    requires_exact_inventory BOOLEAN NOT NULL,
    actual_source_qr VARCHAR(200),
    fulfillment_notes VARCHAR(500),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id),
    FOREIGN KEY (source_location_id) REFERENCES locations(id),
    FOREIGN KEY (destination_location_id) REFERENCES locations(id)
);

CREATE INDEX idx_order_item_order ON order_items(order_id);
CREATE INDEX idx_order_item_product ON order_items(product_id);
CREATE INDEX idx_order_item_inventory ON order_items(inventory_item_id);
CREATE INDEX idx_order_item_status ON order_items(status);
CREATE INDEX idx_order_item_line_number ON order_items(order_id, line_number);

CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    order_id BIGINT NOT NULL,
    old_status VARCHAR(20),
    new_status VARCHAR(20) NOT NULL,
    changed_by BIGINT NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    reason VARCHAR(1000),
    notes VARCHAR(1000),
    system_generated BOOLEAN,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (changed_by) REFERENCES users(id)
);

CREATE INDEX idx_order_status_history_order ON order_status_history(order_id);
CREATE INDEX idx_order_status_history_user ON order_status_history(changed_by);
CREATE INDEX idx_order_status_history_date ON order_status_history(changed_at);
CREATE INDEX idx_order_status_history_status ON order_status_history(new_status);

CREATE TABLE qr_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version BIGINT,
    code VARCHAR(100) NOT NULL UNIQUE,
    type VARCHAR(20) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    data TEXT,
    metadata TEXT,
    active BOOLEAN NOT NULL,
    expires_at TIMESTAMP,
    last_scanned TIMESTAMP,
    scan_count BIGINT NOT NULL,
    format VARCHAR(10),
    size INT,
    error_correction VARCHAR(1),
    generated_by VARCHAR(50),
    generation_reason VARCHAR(200),
    image_path VARCHAR(500),
    description VARCHAR(500),
    custom_data TEXT
);

CREATE INDEX idx_qr_code ON qr_codes(code);
CREATE INDEX idx_qr_type ON qr_codes(type);
CREATE INDEX idx_qr_entity_type ON qr_codes(entity_type);
CREATE INDEX idx_qr_entity_id ON qr_codes(entity_id);
CREATE INDEX idx_qr_active ON qr_codes(active);
CREATE INDEX idx_qr_expires_at ON qr_codes(expires_at);
