package com.qrware.domain.qr;

import com.qrware.domain.common.BaseEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

/**
 * QRCodeData entity for managing QR codes in the system
 */
@Entity
@Table(name = "qr_codes", indexes = {
    @Index(name = "idx_qr_code", columnList = "code"),
    @Index(name = "idx_qr_type", columnList = "type"),
    @Index(name = "idx_qr_entity_type", columnList = "entity_type"),
    @Index(name = "idx_qr_entity_id", columnList = "entity_id"),
    @Index(name = "idx_qr_active", columnList = "active"),
    @Index(name = "idx_qr_expires_at", columnList = "expires_at")
})
public class QRCodeData extends BaseEntity {

    @Column(name = "code", unique = true, nullable = false, length = 100)
    @NotBlank(message = "QR code is required")
    @Size(max = 100, message = "QR code must not exceed 100 characters")
    private String code;

    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 20)
    private QRCodeType type;

    @Column(name = "entity_type", nullable = false, length = 50)
    @NotBlank(message = "Entity type is required")
    @Size(max = 50, message = "Entity type must not exceed 50 characters")
    private String entityType;

    @Column(name = "entity_id", nullable = false)
    private Long entityId;

    @Column(name = "data", columnDefinition = "TEXT")
    private String data;

    @Column(name = "metadata", columnDefinition = "TEXT")
    private String metadata;

    @Column(name = "active", nullable = false)
    private Boolean active = true;

    @Column(name = "expires_at")
    private LocalDateTime expiresAt;

    @Column(name = "last_scanned")
    private LocalDateTime lastScanned;

    @Column(name = "scan_count", nullable = false)
    private Long scanCount = 0L;

    @Column(name = "format", length = 10)
    @Size(max = 10, message = "Format must not exceed 10 characters")
    private String format = "PNG";

    @Column(name = "size")
    private Integer size = 300;

    @Enumerated(EnumType.STRING)
    @Column(name = "error_correction", length = 1)
    private ErrorCorrectionLevel errorCorrectionLevel = ErrorCorrectionLevel.M;

    @Column(name = "generated_by", length = 50)
    @Size(max = 50, message = "Generated by must not exceed 50 characters")
    private String generatedBy;

    @Column(name = "generation_reason", length = 200)
    @Size(max = 200, message = "Generation reason must not exceed 200 characters")
    private String generationReason;

    @Column(name = "image_path", length = 500)
    @Size(max = 500, message = "Image path must not exceed 500 characters")
    private String imagePath;

    @Column(name = "description", length = 500)
    @Size(max = 500, message = "Description must not exceed 500 characters")
    private String description;

    @Column(name = "custom_data", columnDefinition = "TEXT")
    private String customData;

    // Constructors
    public QRCodeData() {}

    public QRCodeData(String code, QRCodeType type, String entityType, Long entityId) {
        this.code = code;
        this.type = type;
        this.entityType = entityType;
        this.entityId = entityId;
    }

    // Business methods
    public boolean isExpired() {
        return expiresAt != null && expiresAt.isBefore(LocalDateTime.now());
    }

    public boolean isValid() {
        return active && !isExpired();
    }

    public void incrementScanCount() {
        this.scanCount++;
        this.lastScanned = LocalDateTime.now();
    }

    public void deactivate() {
        this.active = false;
    }

    public void activate() {
        this.active = true;
    }

    public void setExpiration(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    public void setExpirationDays(int days) {
        this.expiresAt = LocalDateTime.now().plusDays(days);
    }

    public void setExpirationHours(int hours) {
        this.expiresAt = LocalDateTime.now().plusHours(hours);
    }

    public long getDaysSinceLastScan() {
        if (lastScanned == null) {
            return -1;
        }
        return java.time.temporal.ChronoUnit.DAYS.between(lastScanned.toLocalDate(), LocalDateTime.now().toLocalDate());
    }

    public long getHoursSinceLastScan() {
        if (lastScanned == null) {
            return -1;
        }
        return java.time.temporal.ChronoUnit.HOURS.between(lastScanned, LocalDateTime.now());
    }

    public boolean isRecentlyScanned(int hours) {
        return lastScanned != null && lastScanned.isAfter(LocalDateTime.now().minusHours(hours));
    }

    public boolean isFrequentlyScanned(long threshold) {
        return scanCount >= threshold;
    }

    public String getQRCodeUrl() {
        return "/api/qr-codes/" + code + "/image";
    }

    public String getEntityReference() {
        return entityType + ":" + entityId;
    }

    public void updateMetadata(String key, String value) {
        // Simple key-value metadata storage (could be improved with JSON)
        if (metadata == null) {
            metadata = key + "=" + value;
        } else {
            metadata += ";" + key + "=" + value;
        }
    }

    public String getMetadataValue(String key) {
        if (metadata == null) {
            return null;
        }
        
        String[] pairs = metadata.split(";");
        for (String pair : pairs) {
            String[] keyValue = pair.split("=", 2);
            if (keyValue.length == 2 && keyValue[0].equals(key)) {
                return keyValue[1];
            }
        }
        return null;
    }

    // Getters and Setters
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public QRCodeType getType() {
        return type;
    }

    public void setType(QRCodeType type) {
        this.type = type;
    }

    public String getEntityType() {
        return entityType;
    }

    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    public Long getEntityId() {
        return entityId;
    }

    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getMetadata() {
        return metadata;
    }

    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public LocalDateTime getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    public LocalDateTime getLastScanned() {
        return lastScanned;
    }

    public void setLastScanned(LocalDateTime lastScanned) {
        this.lastScanned = lastScanned;
    }

    public Long getScanCount() {
        return scanCount;
    }

    public void setScanCount(Long scanCount) {
        this.scanCount = scanCount;
    }

    public String getFormat() {
        return format;
    }

    public void setFormat(String format) {
        this.format = format;
    }

    public Integer getSize() {
        return size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }

    public ErrorCorrectionLevel getErrorCorrectionLevel() {
        return errorCorrectionLevel;
    }

    public void setErrorCorrectionLevel(ErrorCorrectionLevel errorCorrectionLevel) {
        this.errorCorrectionLevel = errorCorrectionLevel;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }

    public String getGenerationReason() {
        return generationReason;
    }

    public void setGenerationReason(String generationReason) {
        this.generationReason = generationReason;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCustomData() {
        return customData;
    }

    public void setCustomData(String customData) {
        this.customData = customData;
    }

    @Override
    public String toString() {
        return "QRCodeData{" +
                "code='" + code + '\'' +
                ", type=" + type +
                ", entityType='" + entityType + '\'' +
                ", entityId=" + entityId +
                ", active=" + active +
                ", scanCount=" + scanCount +
                '}';
    }
}